import {
  AppWindow,
  Building2,
  LayoutDashboard,
  LayoutTemplate,
  LifeBuoy,
  Palette,
  RefreshCw,
  TrendingUp,
  Webhook,
} from 'lucide-react'
import type { Service } from '@/types'

export const services: Service[] = [
  {
    id: 'kurumsal-web-sitesi',
    title: 'Kurumsal Web Sitesi',
    description:
      'Markanızı güvenilir ve profesyonel biçimde temsil eden, hızlı, mobil uyumlu ve yönetilebilir kurumsal web siteleri.',
    features: [
      'Kuruma özel tasarım',
      'Mobil uyumluluk',
      'SEO altyapısı',
      'İçerik yönetim paneli',
      'Hız optimizasyonu',
      'İletişim ve teklif formları',
    ],
    cta: 'Kurumsal Site Detayları',
    icon: Building2,
    accent: '#3d9bff',
    formValue: 'kurumsal-web-sitesi',
    span: 'wide',
  },
  {
    id: 'ozel-web-sitesi',
    title: 'İhtiyaca Özel Web Sitesi',
    description:
      'Standart hazır şablonların karşılamadığı ihtiyaçlar için tamamen işletmenize özel tasarlanan web projeleri.',
    features: [
      'Özel kullanıcı deneyimi',
      'Kuruma özel fonksiyonlar',
      'Harici servis entegrasyonları',
      'Çok dilli yapı',
      'Üyelik ve kullanıcı sistemleri',
      'Geliştirilebilir mimari',
    ],
    cta: 'Projenizi Anlatın',
    icon: LayoutTemplate,
    accent: '#22d3ee',
    formValue: 'ozel-web-sitesi',
    span: 'normal',
  },
  {
    id: 'web-uygulamasi',
    title: 'Web Uygulaması Geliştirme',
    description:
      'İş süreçlerini dijitalleştiren, zaman kazandıran ve işletmenin çalışma biçimine uyum sağlayan web tabanlı uygulamalar.',
    features: [
      'Yönetim panelleri',
      'Müşteri portalları',
      'Rezervasyon sistemleri',
      'Raporlama ekranları',
      'Operasyon takip sistemleri',
      'Özel CRM çözümleri',
      'API geliştirme ve entegrasyonlar',
    ],
    cta: 'Uygulama Fikrinizi Konuşalım',
    icon: AppWindow,
    accent: '#a78bfa',
    formValue: 'web-uygulamasi',
    span: 'wide',
  },
  {
    id: 'site-yenileme',
    title: 'Mevcut Siteyi Yenileme',
    description:
      'Eski, yavaş veya mobil cihazlarda kötü çalışan web sitelerini modern teknolojilerle yeniden tasarlama ve geliştirme.',
    features: [
      'Tasarım yenileme',
      'Mobil uyumluluk',
      'Performans iyileştirme',
      'Teknik altyapı yenileme',
      'SEO kayıplarını azaltan geçiş',
      'Yönetim paneli geliştirme',
    ],
    cta: 'Sitenizi Birlikte İnceleyelim',
    icon: RefreshCw,
    accent: '#34d399',
    formValue: 'site-yenileme',
    span: 'normal',
  },
  {
    id: 'bakim-destek',
    title: 'Bakım ve Teknik Destek',
    description:
      'Yayındaki web projelerinin güvenli, güncel ve sorunsuz çalışmasını sağlamak için bakım ve geliştirme hizmetleri.',
    features: [
      'Güncelleme',
      'Hata giderme',
      'Güvenlik kontrolleri',
      'Performans takibi',
      'Yedekleme',
      'Yeni özellik geliştirme',
    ],
    cta: 'Destek Hizmeti Alın',
    icon: LifeBuoy,
    accent: '#fbbf24',
    formValue: 'bakim-destek',
    span: 'normal',
  },
  {
    id: 'yonetim-paneli',
    title: 'Yönetim Paneli Geliştirme',
    description:
      'İçerik, sipariş, randevu veya operasyon verilerinizi tek ekrandan yönetebileceğiniz, yetkilendirilmiş ve kullanımı kolay yönetim panelleri geliştiriyoruz.',
    features: [
      'Rol ve yetki bazlı erişim',
      'Özelleştirilmiş veri tabloları ve filtreler',
      'Raporlama ve dışa aktarma',
      'Bildirim ve onay akışları',
      'İşlem geçmişi ve kayıt izleme',
      'Mobil uyumlu panel arayüzü',
    ],
    cta: 'Panel İhtiyacınızı Anlatın',
    icon: LayoutDashboard,
    accent: '#818cf8',
    formValue: 'yonetim-paneli',
    span: 'normal',
  },
  {
    id: 'api-entegrasyon',
    title: 'API ve Sistem Entegrasyonları',
    description:
      'Muhasebe programınız, kargo firmanız, ödeme altyapınız veya üçüncü parti servislerle mevcut sisteminizi konuşturan API’ler ve entegrasyonlar geliştiriyoruz.',
    features: [
      'REST API geliştirme ve dokümantasyon',
      'Ödeme altyapısı entegrasyonları',
      'Kargo ve lojistik servis entegrasyonları',
      'Muhasebe / ERP sistem bağlantıları',
      'Webhook ve otomasyon akışları',
      'SMS, e-posta ve harita gibi üçüncü parti servisler',
    ],
    cta: 'Entegrasyon İhtiyacınızı Konuşalım',
    icon: Webhook,
    accent: '#fb7185',
    formValue: 'api-entegrasyon',
    span: 'normal',
  },
  {
    id: 'seo-danismanligi',
    title: 'SEO Danışmanlığı',
    description:
      'Web sitenizin arama motorlarında daha görünür olması için teknik SEO, içerik optimizasyonu ve performans iyileştirmesi yapıyoruz.',
    features: [
      'Teknik SEO denetimi ve düzeltmeler',
      'Anahtar kelime ve rakip analizi',
      'Sayfa içi (on-page) optimizasyon',
      'Sayfa hızı ve Core Web Vitals iyileştirmesi',
      'Yapısal veri (schema) uygulaması',
      'Aylık sıralama ve trafik raporlaması',
    ],
    cta: 'SEO Danışmanlığı Alın',
    icon: TrendingUp,
    accent: '#2dd4bf',
    formValue: 'seo-danismanligi',
    span: 'wide',
  },
  {
    id: 'kurumsal-kimlik',
    title: 'Kurumsal Kimlik ve Logo Tasarımı',
    description:
      'Markanızı görsel olarak güçlü ve tutarlı biçimde temsil eden logo, kurumsal kimlik ve marka rehberi çalışmaları yapıyoruz.',
    features: [
      'Logo tasarımı ve vektörel dosyalar',
      'Renk paleti ve tipografi seçimi',
      'Kartvizit ve antetli kağıt tasarımı',
      'Sosyal medya profil şablonları',
      'Marka kullanım rehberi (brand guideline)',
      'Web sitesiyle tutarlı görsel dil',
    ],
    cta: 'Marka Kimliği Oluşturalım',
    icon: Palette,
    accent: '#f472b6',
    formValue: 'kurumsal-kimlik',
    span: 'normal',
  },
]
